export type Claim = { text: string; kind: "Sourced" | "Assumption"; source?: string };
export type Rung = { n: number; name: string; firstAgent: Claim; signOff: Claim; proof: Claim; failure: Claim; runbook: { slug: string; title: string } | null; note?: Claim };

export const RUNGS: Rung[] = [
  { n: 1, name: "Support triage",
    firstAgent: { text: "Inbound request triage: category, urgency with reasons, owner, first reply draft asking for missing ids.", kind: "Sourced", source: "rt-docs-support" },
    signOff: { text: "Support lead sends every customer reply; refunds wait behind an approval.", kind: "Sourced", source: "rt-docs-support" },
    proof: { text: "Time to first response and correct-routing rate on a weekly 20-ticket sample.", kind: "Assumption" },
    failure: { text: "Promising a refund or a date before approval.", kind: "Sourced", source: "rt-docs-support" },
    runbook: { slug: "duplicate-charge", title: "Duplicate charge and refund" } },
  { n: 2, name: "Customer success",
    firstAgent: { text: "Weekly account health note: runs, approvals, overrides, incidents, next step for the champion.", kind: "Assumption" },
    signOff: { text: "CS owner reviews each note before it reaches the customer.", kind: "Assumption" },
    proof: { text: "Share of accounts with a health note every week; renewals with a brief 90 days out.", kind: "Assumption" },
    failure: { text: "Health score trusted when inputs are missing (coverage under 60%).", kind: "Assumption" },
    runbook: null, note: { text: "Support, then customer success, then fraud and risk is the expansion path in the brief, attributed to Gus Trigos's LinkedIn. Not re-verified: LinkedIn blocks signed-out reading.", kind: "Assumption", source: "gus-li" } },
  { n: 3, name: "Implementation",
    firstAgent: { text: "Start with one SOP and one queue with an agreed success measure, built with the customer team.", kind: "Sourced", source: "rt-enterprise" },
    signOff: { text: "Customer ops lead and their security team agree boundaries and approval points before go-live.", kind: "Sourced", source: "rt-enterprise" },
    proof: { text: "First agent live on one queue within the first days of kickoff.", kind: "Sourced", source: "yc-launch" },
    failure: { text: "Starting with a queue that has no agreed success measure.", kind: "Sourced", source: "rt-enterprise" },
    runbook: { slug: "kyb-prep", title: "Merchant onboarding / KYB review prep" } },
  { n: 4, name: "Payouts",
    firstAgent: { text: "Stuck payout trace: processor status, ledger batch, bank deposit, drafted reply.", kind: "Sourced", source: "rt-home" },
    signOff: { text: "A person approves releasing a held payout or booking a ledger entry.", kind: "Sourced", source: "rt-home" },
    proof: { text: "Share of payouts traced to a definite status on the first run; median time to resolution.", kind: "Assumption" },
    failure: { text: "Treating processor 'paid' as received at the bank.", kind: "Assumption" },
    runbook: { slug: "stuck-payout", title: "Stuck payout trace" } },
  { n: 5, name: "Fraud and risk",
    firstAgent: { text: "Alert review packet with signals for and against; no block applied.", kind: "Sourced", source: "rt-docs-fraud" },
    signOff: { text: "Analyst makes every block, release or reserve decision.", kind: "Sourced", source: "rt-docs-fraud" },
    proof: { text: "Packet ready within 1 hour; false-positive rate tracked per rule.", kind: "Assumption" },
    failure: { text: "One-sided packets that only list supporting signals.", kind: "Assumption" },
    runbook: { slug: "card-fraud-alert", title: "Card-fraud alert triage" } },
  { n: 6, name: "Compliance",
    firstAgent: { text: "Sanctions hit and TM alert prep: field-by-field comparison and a who/what/when/where/why/how note.", kind: "Sourced", source: "ofac-faq-screen" },
    signOff: { text: "Compliance officer clears hits and owns every SAR decision.", kind: "Assumption" },
    proof: { text: "Reviewer accepts the prepared note without rework; aged alerts trend down.", kind: "Assumption" },
    failure: { text: "Clearing a hit on name alone; any customer tip-off.", kind: "Sourced", source: "ofac-faq-screen" },
    runbook: { slug: "sanctions-hit", title: "Sanctions-hit review prep" } },
];
